class LessonContentListening{
  static _Part1 part1 = _Part1();
  static _Part2 part2 = _Part2();
  static _Part3 part3 = _Part3();
  static _Part4 part4 = _Part4();
}

class _Part1{
  final String lesson11_VN = '💡 Trong phần này, bạn được yêu cầu xem một bức tranh và chọn câu mô tả bức tranh đó đúng nhất. Để có thể chọn câu trả lời đúng, bạn nên nghĩ đến chủ đề của bức tranh và các câu có thể.';
  final String lesson12_VN = '💡 Trước khi bắt đầu phần này, hãy nghĩ về chủ đề của bức tranh cũng như động não các danh từ và động từ liên quan đến bức tranh. Bạn nên làm điều này bởi vì hầu hết các yếu tố gây xao nhãng trong phần 1 của TOEIC đều liên quan đến việc dùng sai danh từ hoặc động từ.\n💡 Trước khi nghe, bạn cũng nên dự đoán những câu có thể xảy ra. Hầu hết các câu là về:\n+ Các hoạt động\nE.g. The man is writing an email.\n+ Tình hình chung\nE.g. The meal is ready.\n+ Mối quan hệ không gian\nE.g. next to, near, across from, etc.\n💡 Tập trung khi nghe và chọn câu đúng.';
  final String lesson21_VN = '💡 Trong phần này, bạn được yêu cầu xem một bức tranh và chọn câu mô tả bức tranh đó đúng nhất. Để đạt điểm tối đa trong phần này, bạn cần chọn câu có động từ mô tả chính xác nhất những gì nhìn thấy trong bức tranh.';
  final String lesson22_VN = '💡 Lắng nghe cẩn thận để kiểm tra xem động từ có liên quan đến bức tranh không: Âm thầm lặp lại câu khi bạn nghe và so sánh động từ được sử dụng với những gì bạn nhìn thấy trong bức tranh.\n\n💡 Chọn câu trả lời nhanh chóng: Khi bạn nghe, hãy giơ bút chì lên các câu trả lời. Cố gắng lặp lại các câu. Nếu bạn nghĩ rằng một câu nào đó có thể đúng, hãy giữ bút của bạn trên lựa chọn câu trả lời đó. Đừng di chuyển nó cho đến khi bạn nghe thấy một sự lựa chọn tốt hơn. Trả lời nhanh và chuyển sang câu hỏi tiếp theo.';
  final String lesson31_VN = '💡 Trong phần này, bạn được yêu cầu nhìn vào một bức tranh và chọn câu mô tả đúng nhất về bức tranh. Để đạt điểm cao hơn trong phần này, bạn cần nghe kỹ từng chi tiết vì hầu hết các lựa chọn sai trong phần này sẽ sử dụng một số từ chủ ngữ, động từ và tân ngữ đúng và một số từ sai.';
  final String lesson32_VN = '💡 Nghe các từ SVO: Hầu hết các câu hỏi Part 1 của TOEIC đều theo chủ ngữ, động từ hoặc mẫu chủ ngữ, động từ, tân ngữ (SVO). Lắng nghe cẩn thận các từ SVO và so sánh các từ bạn nghe được với những từ trong hình.\n\n💡 Nghe sai chủ ngữ, động từ và tân ngữ: Một số người làm mất tập trung sử dụng từ khóa chính xác và từ khóa không chính xác. Nếu nghe sai, bạn có thể bỏ qua lựa chọn đáp án đó ngay lập tức.';
  final String lesson41_VN = '💡 Trong phần này, sự hiểu biết của bạn về vị trí và hướng sẽ được kiểm tra. Để đạt điểm cao hơn trong phần này, bạn cần phải làm quen với các từ được sử dụng để mô tả nơi mọi thứ đang ở và nơi chúng sẽ đến, điều này sẽ giúp bạn đạt điểm cao trong phần thi này.';
  final String lesson42_VN = '💡 Nghe giới từ: Nhiều câu trong TOEIC Part 1 nói về vị trí của người hoặc đồ vật trong bức tranh. Hãy lắng nghe cẩn thận những giới từ sai trong những bức tranh này.\n\n💡 Hãy cẩn thận với những âm tương tự: Nếu bạn nghe thấy một từ có âm giống với một từ mà bạn có thể nhìn thấy hoặc tưởng tượng trong hình, đó có thể là một yếu tố khiến bạn mất tập trung.';
}

class _Part2{
  final String lesson11_VN = '💡 Trong phần này của bài kiểm tra, bạn sẽ thường nghe những câu hỏi trực tiếp. Câu trả lời đúng thường sẽ không phải là câu trả lời Yes, No hoặc Don\'t know, và thường sẽ ở một thì khác.';
  final String lesson12_VN = '💡 Thông thường các câu hỏi trực tiếp sẽ không được trả lời là Yes, No hoặc Don\'t know: Hãy tìm các phương án sử dụng các từ khác nhau để diễn đạt những ý nghĩa này.\n\n💡 Thông thường, câu hỏi và lựa chọn câu trả lời sẽ ở các thì của động từ khác nhau: Đừng mong đợi ngữ pháp của câu hỏi để phù hợp với câu trả lời. E.g: Are you going tonight? -> I\'ve made other plans.\n\n💡 Những từ phân tâm sử dụng các từ giống nhau (hoặc có âm tương tự) thường gặp trong TOEIC Phần 2: Hãy cẩn thận khi chọn các câu trả lời sử dụng các từ giống hoặc có âm tương tự.\n\n💡 Trí nhớ ngắn hạn Điều quan trọng là: Lặp lại từng câu trả lời trong đầu bạn và kiểm tra xem nó có trả lời câu hỏi hay có cùng một từ/âm thanh tương tự làm mất tập trung không.';
  final String lesson21_VN = '💡 Trong phần thi này, bạn được yêu cầu chọn câu trả lời đúng cho các câu hỏi về thời gian và địa điểm thường gặp trong bài thi TOEIC. Câu hỏi "Where" thường chứa cụm từ where, câu hỏi "When" thường chứa cụm từ How long, When và What time.';
  final String lesson22_VN = '💡 Các câu trả lời cho câu hỏi về thời gian và địa điểm thường sử dụng các từ đánh dấu phổ biến: Việc làm quen với các giới từ và các từ khác phổ biến trong các câu trả lời này sẽ giúp bạn chọn câu trả lời đúng.\n\n💡 Câu trả lời đúng có thể sử dụng các câu trả lời rất ngắn hoặc không xác định: Hãy lắng nghe những câu hỏi này và quyết định loại câu hỏi mà họ có thể trả lời.\n\n💡 Học cách xác định các câu hỏi về vị trí: Thông thường chúng liên quan đến từ where, nhưng các từ khác cũng có thể được sử dụng khi hỏi đường đến một địa điểm. Câu hỏi "Where" đôi khi có thể có câu trả lời "Directions"; vì vậy, hãy lắng nghe kỹ phần này.\n\n💡 Tìm hiểu cách xác định câu hỏi "When". Thông thường, câu hỏi "When" bao gồm các cụm từ How long, When và What time.';
  final String lesson31_VN = '💡 Trong phần thi này, bạn được yêu cầu chọn câu trả lời đúng cho các câu hỏi về đề nghị, yêu cầu và ý kiến.';
  final String lesson32_VN = '💡 Tương tác xã hội, bao gồm lời đề nghị, yêu cầu và ý kiến, là một đặc điểm chung của Phần 2: Hãy lưu ý đến ngôn ngữ thường được sử dụng trong những tình huống này.\n\n💡 Những yếu tố gây phân tâm phổ biến cho phần này bao gồm việc sử dụng cùng một từ/âm tương tự hoặc nghĩa không chính xác : Nhận thấy những loại câu trả lời sai này có thể giúp bạn chọn câu trả lời đúng.\n\n💡 Hãy lặp lại thầm từng câu hỏi và lựa chọn trả lời sau khi bạn nghe thấy. Điều này sẽ giúp bạn ghi nhớ và so sánh ý nghĩa.';
  final String lesson41_VN = '💡 Với loại câu hỏi này, bạn được yêu cầu chọn câu trả lời đúng cho các câu hỏi thực tế. Hãy suy nghĩ cẩn thận về những gì câu hỏi đang thực sự yêu cầu. Một số câu trả lời có thể liên quan chặt chẽ đến chủ đề trong câu hỏi, nhưng không trả lời trực tiếp.';
  final String lesson42_VN = '💡 Các câu trả lời trong bài thi TOEIC không phải lúc nào cũng trả lời trực tiếp câu hỏi. Do đó, bạn cần lắng nghe câu trả lời với các chi tiết hoặc giải thích liên quan.\n\n💡 Đừng mong đợi các thì luôn giống nhau. Ví dụ: câu trả lời cho câu hỏi ở tương lai hoặc hiện tại có thể giải thích điều gì đó trong quá khứ.\n\n💡 Vì trọng tâm trong TOEIC phần 2 là - ý nghĩa. Bạn nên nghe các từ khóa (danh từ/động từ/từ nghi vấn) để giúp bạn tránh những yếu tố khiến bạn phân tâm và tìm ra lựa chọn trả lời chính xác.\n\n💡 Hãy chú ý đến những yếu tố khiến bạn mất tập trung phổ biến: Làm quen với cách mà các lựa chọn trả lời sai có thể khiến bạn mất tập trung có thể giúp bạn thực hiện một lựa chọn tốt.';
}

class _Part3{
  final String lesson11_VN = '💡 Trong phần này của bài kiểm tra, bạn nên đọc lướt các câu hỏi và trả lời các lựa chọn để dự đoán những gì bạn sẽ nghe.';
  final String lesson12_VN = '💡 Sử dụng thời gian trước khi nghe để dự đoán ngữ cảnh. Điều này có thể làm cho việc nghe dễ dàng hơn. Sử dụng thông tin chính trong các lựa chọn câu trả lời để đoán sơ bộ về những gì bạn sắp nghe.\n\n💡 Hãy lắng nghe cẩn thận và chọn câu trả lời đúng.';
  final String lesson21_VN = '💡 Trong phần thi này, đoạn ghi âm thường có thể sử dụng các từ giống hoặc cùng nghĩa với các từ trong các lựa chọn trả lời. Điều này có thể khiến bạn chọn một câu trả lời không chính xác. Hãy cẩn thận không chọn một câu trả lời chỉ vì bạn đã nghe điều gì đó tương tự trong bài nghe.';
  final String lesson22_VN = '💡 TOEIC Part 3 đôi khi sử dụng cùng một từ trong phần ghi âm và các lựa chọn trả lời, nhưng với một ý nghĩa khác. Do đó, hãy cẩn thận nếu bạn nghe thấy những từ giống nhau trong cuộc trò chuyện cũng như trong các lựa chọn câu trả lời.\n\n💡 Câu trả lời cho các câu hỏi của Phần 3 thường sử dụng các từ khác với đoạn ghi âm.\n\n💡 Nghe xem ai nói gì: Thường thì lựa chọn câu trả lời sẽ có từ khóa được sử dụng bởi một trong những người nói, nhưng đó có thể không phải là người nói được chỉ định trong câu hỏi. Nhận thấy điều này có thể giúp bạn phát hiện ra những yếu tố gây xao nhãng.';
  final String lesson31_VN = '💡 Các câu trả lời cho nhiều câu hỏi trong phần này của bài kiểm tra không được nêu trực tiếp. Bạn sẽ phải lắng nghe cẩn thận và sử dụng kiến thức về từ vựng và ngữ cảnh liên quan để chọn nhiều câu trả lời.';
  final String lesson32_VN = '💡 Đôi khi câu trả lời không được nêu ra - trực tiếp trong đoạn văn: Trước khi nghe, hãy nghĩ về các từ khác liên quan đến các lựa chọn câu trả lời và lắng nghe để suy ra nghĩa chung.\n\n💡 Một số câu hỏi rõ ràng yêu cầu bạn suy luận về tình huống: Hãy tìm dấu hiệu suy luận phổ biến: Điều gì có thể được nói/ngụ ý/suy ra ...? và lắng nghe thông tin liên quan trong đoạn ghi âm.';
  final String lesson41_VN = '💡 Trong một số đoạn ghi âm trong TOEIC Part 3, bạn sẽ gặp phải những phản ứng tiêu cực. Làm quen với ngôn ngữ và cách tổ chức phổ biến đối với các câu trả lời phủ định có thể giúp bạn chọn câu trả lời đúng. Điều quan trọng là phải hiểu cuộc trao đổi đầu tiên, vì điều này có thể chứa câu trả lời cho câu hỏi đầu tiên.';
  final String lesson42_VN = '💡 Các cuộc trò chuyện liên quan đến việc nói "No" đôi khi xuất hiện trong bài thi TOEIC: Học cách xác định các cụm từ từ chối và từ chối, đồng thời lắng nghe cẩn thận thông tin theo sau chúng. Thông tin này thường là trọng tâm của một trong các câu hỏi.\n\n💡 Hầu hết các cuộc hội thoại trong Phần 3 đều bắt đầu bằng một câu hỏi hoặc yêu cầu: Hãy lắng nghe cẩn thận những gì người nói đầu tiên nói và câu trả lời, vì chúng có thể liên quan đến câu hỏi đầu tiên.';
}

class _Part4{
  final String lesson11_VN = '💡 Trước khi nghe, bạn nên đọc lướt qua các câu hỏi và lựa chọn trả lời để dự đoán những gì bạn sẽ nghe cũng như xác định các phần chính của bài nói.';
  final String lesson12_VN = '💡 Bài kiểm tra TOEIC thường sử dụng các từ khác nhau trong các lựa chọn câu trả lời và đoạn ghi âm: Trước khi bạn nghe, hãy thử tưởng tượng những cách khác mà câu trả lời lựa chọn có thể được nói.\n\n💡 Lưu ý từ khóa: Chọn ra các từ khóa từ các lựa chọn câu trả lời sẽ giúp bạn dự đoán những gì bạn sẽ nghe và tập trung vào những gì bạn phải lắng nghe.\n\n💡 Trả lời câu hỏi ngay khi bạn nghe câu trả lời: Đừng đợi giọng nói nói với bạn. Trả lời nhanh, sau đó sử dụng 35-40 giây giữa các cuộc trò chuyện để đọc lướt các câu hỏi tiếp theo.';
  final String lesson21_VN = '💡 Trong phần này của bài kiểm tra, bạn cần xử lý các câu hỏi "What". Đây là dạng câu hỏi rất thường gặp trong bài thi TOEIC. Đôi khi câu hỏi "Cái gì" yêu cầu khái quát hoặc ý chính của bài nói. Những lần khác họ yêu cầu thông tin cụ thể.';
  final String lesson22_VN = '💡 Một số câu hỏi "What" trong Phần 4 yêu cầu bạn hiểu ý chính của bài nói: Lắng nghe những từ cho bạn biết thông tin về người nói, địa điểm và chủ đề.\n\n💡 Các câu hỏi "What" khác yêu cầu bạn lắng nghe cụ thể thông tin: Luôn đọc lướt câu hỏi và trả lời các lựa chọn trước khi nghe. Xác định các từ khóa và lắng nghe cẩn thận những từ này.\n\n💡 Câu trả lời trong Phần 4 thường xuất hiện theo thứ tự xuất hiện trong bài nói: Hãy nghe câu trả lời theo thứ tự.\n\n💡 Đánh dấu câu trả lời khi bạn nghe: Nếu bạn nghe thấy câu trả lời điều đó chắc chắn là chính xác, hãy đánh dấu nó khi bạn nghe. Trả lời tất cả các câu hỏi càng nhanh càng tốt.';
  final String lesson31_VN = '💡 Trong phần thi này, bạn được yêu cầu trả lời các câu hỏi với các con số và số lượng. Ngoài ra, bạn cần làm quen với việc trình bày lại.';
  final String lesson32_VN = '💡 Lựa chọn câu trả lời đúng thường sử dụng các từ khác với những gì bạn sẽ nghe: Hãy lưu ý điều này và lắng nghe ý nghĩa chứ không chỉ các từ khóa.\n\n💡 Các câu hỏi về thông tin cụ thể đôi khi xuất hiện theo cùng thứ tự xuất hiện trong bài nghe: Tập trung vào các câu hỏi theo thứ tự. Khi bạn nghe thấy câu trả lời, hãy đánh dấu câu trả lời đó và tiếp tục ngay lập tức.\n\n💡 Hãy cẩn thận với các câu hỏi liên quan đến số lượng và số lượng: Đọc câu hỏi và ghi chú cẩn thận nội dung câu hỏi, sau đó đọc nhanh các lựa chọn trả lời. Khi bạn nghe thấy một trong các số trong bản ghi âm, hãy quyết định xem số đó có trả lời câu hỏi hay không.\n\n💡 Hãy cẩn thận với các yếu tố làm phân tâm âm thanh trong các số kết thúc bằng -teen hoặc -ty\n\nE.g: 13 sounds like 30.';
  final String lesson41_VN = '💡 Trong phần này của bài kiểm tra, bạn cần làm quen với cách trình bày lại liên quan đến câu hỏi "How" và "Why". Động não từ vựng liên quan đến các lựa chọn câu trả lời có thể giúp bạn xác định thông tin trong bài nói trình bày lại lựa chọn câu trả lời.';
  final String lesson42_VN = '💡 Động não các từ liên quan: Trước khi bạn nghe bài nói, hãy cố gắng nhìn vào các lựa chọn câu trả lời và nghĩ ra những cách khác mà lựa chọn câu trả lời có thể được nói.\n\n💡 Nghe các từ liên quan và cách diễn đạt lại: Câu trả lời đúng cho "How" hoặc câu hỏi "Why" đôi khi là cách trình bày lại từ ngữ trong bản ghi âm. Lắng nghe những từ có nghĩa tương tự với một trong các lựa chọn trả lời.\n\n💡 Hãy cẩn thận với những từ khiến bạn phân tâm: Nếu bạn thấy cùng một từ trong lựa chọn trả lời như bạn đã nghe trong đoạn ghi âm. suy nghĩ cẩn thận nếu nó có liên quan đến ý nghĩa của câu hỏi trước khi đưa ra lựa chọn của bạn.';
}