class LessonContentWriting{
  static _Question15 question15 = _Question15();
  static _Question67 question67 = _Question67();
  static _Question8 question8 = _Question8();
}

class _Question15{
  final String lesson11_VN = 'Thời gian để trả lời 5 câu hỏi là 8 phút, thí sinh có thể sử dụng khoảng thời gian chuyển từ câu hỏi này sang câu hỏi khác để kiểm tra và sửa lỗi ngữ pháp';
  final String lesson12_VN = '';
  final String lesson13_VN = '';
  final String lesson21_VN = '• The appropriate use of grammar\n• The relevance of the sentence to the picture.';
  final String lesson22_VN = '• Tiêu chuẩn xác dịnh độ chính xác của ngữ pháp:\n -Câu được viết phải bao gồm cả hai từ trong tâm đã cho.\n -Sẽ bị trừ điểm nếu trong câu có lỗi ngữ pháp liên quan đến từ trọng tâm đã cho.\n -Sẽ không bị trừ điểm nếu có lỗi nhỏ phẩn câu không liên quan đến từ trọng tâm đã cho.\n\n• Nội dung liên quan đến bức hình:\n -Câu được viết không chỉ miêu tả sự thật thể hiện trong bức hình mà còn nêu ra được điều có thể suy luận từ nội dung của bức hình.';
  final String lesson23_VN = '• Khi viết câu trả lời:\nBạn phải sử dụng hai từ trọng tâm được cho dưới bức hình để viết một cầu và nội dung câu đó phải liên quan đến bức hình.\nBạn có thể viết một câu đơn giản nếu sử dụng thích hợp hai từ trọng tâm được cho.\n\n• Phân bố thời gian:\nThời gian dành cho cả 5 câu hỏi là 8 phút; có nghĩa là bạn có 1 phút 30 giây cho mỗi câu. Tuy nhiên, bạn nên dành 1 phút cho mỗi câu và 3 phút còn lại để kiểm tra và sửa lỗi ngữ pháp. Nếu có câu nào bạn không thể viết trong vòng 1 phút thì hãy chuyển sang làm câu khác, rồi quay lại câu đó trong khoảng thời gian còn lại.\n\n• Khi sửa chữa câu trả lời:\nBạn có thể sử dụng các công cụ hỗ trợ khi viết câu trả lời để tiết kiệm thời gian. Chẳng hạn, bạn có thể cắt (cut) những thổ cần thiết để dán (paste) vào nơi bạn muốn.\nTrong phần cầu có từ trọng tâm, bạn không được phép phạm bất cứ lối nào, ngay cả lối chính tả. Vì vậy, bạn cần phải đặc biệt chú ý đến phần này.';
}

class _Question67{
  final String lesson11_VN = '';
  final String lesson12_VN = '';
  final String lesson21_VN = '• The quality and variety of your sentences, vocabulary, and organization.';
  final String lesson22_VN = '• Tiêu chuẩn để đánh giá và cho điểm là bố cục, năng lực từ vựng, chất lượng và tính đa dạng của câu.\n\n• Chất lượng và tính đa dạng của câu:\n - Đánh giá khả năng sử dụng cấu trúc cấu đa dạng bao gồm câu đơn, câu ghép và câu phức\n\n• Năng lực từ vựng:\n - Đánh giá xem thí sinh có khả năng sử dụng từ ngữ đã dạng và thích hợp với tình huống hay không.\n\n• Bố cục:\n - Đánh giá nội dung của email có nhất quán và lôgic này không.';
  final String lesson23_VN = '• Khi đọc email:\n - Nắm bắt tình huống chung của toàn bộ email thông qua người gửi (sau From), người nhận (sau To) và mục đích của email (sau Subject), đồng thời hiểu được nội dung cụ thể của email.\n - Hiểu chính xác vấn đề: Bạn đứng ở cương vị nào để viết email trả lời\n\n• Khi viết email trả lời:\nNgười gửi, người nhận là ai không phải là yếu tố quyết định điểm số, vì vậy hãy tập trung vào chủ đề đã cho để trình bày nội dung chính xác, rõ rằng. Trọng tâm của câu hỏi viết email trong kỳ thi TOEIC không phải để đánh giá xem người viết có khả năng trình bày đầy đủ hình thức của email, mà là đánh giá xem email đó có truyền đạt mạch lạc những nội dung như yêu cấu, hỏi, để nghỉ, cung cấp thông tin, v.v. liên quan đến chủ để được cho hay không. Do đó, bạn không cần phải để tâm quá nhiều vào hình thức của email, mà hãy tập trung suy nghĩ về các ý tưởng liên quan đến chủ đề và trình bày chủ đề đó một cách hiệu quả trong email của mình.';
}

class _Question8{
  final String lesson11_VN = 'Trong vòng 30 phút bạn phải lập dàn ý viết và chính sửa bài luận.';
  final String lesson12_VN = '';
  final String lesson21_VN = '• Whether your opinion is supported with reasons and/or examples.\n• Grammar, vocabulary, and organization.';
  final String lesson22_VN = 'Tiêu chí để đánh giá và cho điểm là cấu tạo toàn bài, năng lực từ vựng, độ chính xác về ngữ pháp và ý kiến có được hỗ trợ bởi các ví dụ hoặc lý do thích hợp hay không.\n\n• Điều quan trọng là bạn phải đưa ra được lý do hợp lý và ví dụ thích hợp để hỗ trợ cho ý kiến của bản thân. Nếu chỉ trình bày ý kiến của mình thì bạn không thể đạt được điểm cao.\n\n• Ngữ pháp: Bạn sẽ không bị trừ. điểm nếu chỉ mắc những lỗi ngữ pháp nhỏ không gây trở ngại cho việc hiểu được ý nghĩa. Tuy nhiên, những lỗi ngữ pháp khiến cho ý nghĩa bạn muốn trình bày trở nên mơ hồ, khó hiểu thì sẽ bị trừ điểm.\n\n• Năng lực từ vựng. Bản phải chứng tỏ khả năng sử dụng từ vùng thích hợp tùy theo tình hướng và khả năng sử dụng từ vùng đã dùng thay vì lập lại những gì đã dùng trước đó.\n\n• Cấu trúc tổng thể Bài viết của bạn phải có tính nhất quán cao và sự liên kết ý tưởng chặt chẽ và lôgic.';
  final String lesson23_VN = '\n💡 Cấu tạo cơ bản của bài luận\n\nTOEIC Writing yêu cầu bạn viết một bài luận có độ dài khoảng 300 từ về các chủ đề liên quan đến sinh hoạt công sở trong khoảng thời gian 30 phút. Để viết được một bài luận hoàn chỉnh thì điều quan trọng là trước hết bạn phải nắm vững cấu trúc cơ bản của bài luận bao gồm phần mở bài, thân bài và kết luận.\n\n• Phần mở bài (Introduction):\nỞ đoạn văn mở đầu, bạn phải giới thiệu cầu luận đề liên quan đến chủ đề được yêu cầu. Câu luận đề có thể là ý kiến của bản thân về chủ đề hoặc là một hay hai câu tóm tắt quan điểm.\n\n• Thân bài (Body):\nỞ phần thân bài, bạn phải nêu lý do cụ thể giải thích tại sao bản thân lại có ý kiến, quan điểm như vậy.\n\n• Kết luận (Conclusion):\nỞ phần kết luận, bạn phải lập lại câu luận để đã trình bày ở phần mở bài nhằm tạo sức thuyết phục với người đọc về ý kiến, quan điểm bản thân bạn đã chọn. Ở phần này, bạn không nên đề cập đến các ý tưởng mới vốn không được trình bày ở phần thân bài.\n\n\n💡 Các giai đoạn viết bài luận\n\n• Hiểu TOPIC\nĐiểm mấu chốt đầu tiên khi viết bài luận là hiểu đúng chủ đề đã cho. Ban chỉ nên bắt đầu viết bài luận sau khi đã nắm bắt chính xác trọng tâm của vấn đề.\n\n• Động não tìm ý tưởng liên quan đến chủ đề\nBạn phải chọn ý tưởng của bản thân sao cho phù hợp với topic cũng như thể loại của câu hỏi ví dụ như kiểu câu hỏi yêu cầu nêu ý kiến đồng ý hay không đồng ý, kiểu tường thuật, kiểu diễn tả ưu - khuyết điểm, v.v. và sau đó suy nghĩ tìm lý do hỗ trợ cho các ý tưởng đó.\n\n•Nắm các ý tưởng chính\nBạn phải ghi chú các ý tưởng đã nghĩ ra và bắt đầu viết câu, đoạn văn sau khi thiết lập được dàn ý của bài luận.\n\n•Viết bài luận thực tế\nBạn phải viết bài luận theo trình tự: Phần mở bài -> Thân bài -> Kết luận, đồng thời phải duy trì tính nhất quán xuyên suốt bài luận.\n\n•Đọc lại\nTrước khi kết thúc, bạn phải đọc lại toàn bộ bài luận để kiểm tra về lỗi ngữ pháp, tính liên kết chặt chẽ, tinh nhất quán nhóm năng của nhức độ hoàn chỉnh của bài luận.';
}