class LessonContentReading{
  static _Part5 part5 = _Part5();
  static _Part6 part6 = _Part6();
  static _Part7 part7 = _Part7();
}

class _Part5{
  final String lesson11_VN = '💡 Phần này bao gồm các câu hỏi trắc nghiệm. Một số câu hỏi yêu cầu bạn chọn phương án đúng để điền vào chỗ trống bằng cách xác định đúng phần phát biểu của từ cần thiết.';
  final String lesson12_VN = '💡 Quyết định phần nào của bài phát biểu (tính từ, trạng từ, danh từ, động từ) là cần thiết. Có một số mẹo để xác định một phần của bài phát biểu là cần thiết. Ví dụ: sử dụng hậu tố (phần cuối của từ) để giúp xác định phần của lời nói.\n\nVí dụ: -ed/-ing/-ful/ -le (adj)\n-ly (adv)\n-ment ( n)\n\n💡 Tìm loại câu trả lời đúng. Một khi bạn biết những gì bạn đang tìm kiếm, hãy lướt qua các lựa chọn câu trả lời để tìm thấy nó. Điều này có thể giúp bạn loại bỏ các câu trả lời sai.';
  final String lesson21_VN = '💡 Phần này yêu cầu bạn chọn câu trả lời đúng để điền vào chỗ trống bằng cách xác định xem chỗ trống ở dạng "gerund" hay "infinitive".';
  final String lesson22_VN = '💡 Nhìn vào động từ trong câu hỏi để quyết định xem câu trả lời cần có động danh từ hay động từ nguyên mẫu.\n\n💡 Tìm lựa chọn đúng loại cho câu trả lời.\n\n💡 Khi chuẩn bị cho kỳ thi, hãy tự làm quen với các cụm từ phổ biến bao gồm động danh từ và động từ nguyên mẫu.';
  final String lesson31_VN = '💡 Trong phần này, bạn được yêu cầu chọn từ chứa dạng đúng của tiền tố hoặc hậu tố để điền vào chỗ trống.';
  final String lesson32_VN = '💡 Học các tiền tố phổ biến có thể giúp bạn đoán nghĩa của những từ bạn không biết. Ví dụ: tiền tố "il" thường được sử dụng trước các từ bắt đầu bằng "L" (Ví dụ: illegal, illegible). Tiền tố "im" thường được sử dụng trước các từ bắt đầu bằng "B, P và M❞ (Ví dụ: imbalanced, impossible, immeasurable)\n\n💡 Học các hậu tố phổ biến có thể giúp bạn xác định danh từ và động từ. Ví dụ: "- tion/ -sion", "ment", "-ance/-ence" thường là hậu tố của danh từ. Trong khi đó, "-(i)fy" và "-ise/- ize" thường là hậu tố của động từ.';
  final String lesson41_VN = '💡 Phần này yêu cầu bạn chọn đúng loại đại từ trong bốn phương án A, B, C, D để điền vào chỗ trống.';
  final String lesson42_VN = '💡 Xác định loại đại từ nào cần điền vào chỗ trống.\n\n+ Đối với đại từ nhân xưng, nếu chỗ trống thay thế chủ ngữ thì đó là đại từ chủ ngữ (I, She, He, v.v.). Nếu chỗ trống thay thế một tân ngữ, thì đó là đại từ tân ngữ (me, him, her).\n\n+ Đối với tính từ sở hữu, nếu chỗ trống bổ nghĩa cho danh từ, thì đó là tính từ sở hữu (my, your, our, v.v.). Nếu chỗ trống thay thế một danh từ, thì đó là đại từ sở hữu (mine, yours, ours, v.v.)\n\n💡 Chọn dạng đúng của đại từ.';
}

class _Part6{
  final String lesson11_VN = '💡 Trong phần này, bạn sẽ được yêu cầu chọn dạng đúng của động từ bằng cách sử dụng ngữ cảnh của câu hoặc toàn bộ đoạn văn.';
  final String lesson12_VN = '💡 Nhìn vào câu (và phần còn lại của đoạn văn nếu cần) để quyết định xem cần dùng thì nào.\n\n💡 Chọn phương án đúng. Một khi bạn biết dạng động từ nào là cần thiết, hãy lướt qua các lựa chọn trả lời để tìm nó.';
  final String lesson21_VN = '💡 Phần này yêu cầu bạn chọn câu trả lời đúng để điền vào chỗ trống bằng cách xác định phần nào của bài phát biểu được yêu cầu.';
  final String lesson22_VN = '💡 Nhìn vào câu hỏi và quyết định phần nào của bài phát biểu là cần thiết. Có một số mẹo để xác định phần nào của bài phát biểu là cần thiết. Ví dụ: sử dụng hậu tố.\n\n+ Những từ kết thúc bằng "ful, ous, could, ic, v.v." thường là tính từ. Ngoài ra, tính từ thường đi sau động từ "to be" hoặc các động từ khác liên quan đến giác quan như look, smell, taste, v.v.\n\n+ Những từ kết thúc bằng "ly" thường là trạng từ.';
  final String lesson31_VN = '💡 Trong phần này, bạn được yêu cầu chọn dạng động từ đúng để điền vào chỗ trống bằng cách sử dụng các gợi ý trong câu và đoạn văn.';
  final String lesson32_VN = '💡 Dựa vào tín hiệu trong câu hỏi cũng như phần còn lại của bài văn để chọn dạng đúng. Ví dụ, tín hiệu của thì hiện tại tiếp diễn là những từ như "now", "at present", "at the moment", v.v. hoặc tín hiệu của thì hiện tại hoàn thành là những từ và cụm từ như "since  + thời điểm", " for + khoảng thời gian", "ever", v.v.';
  final String lesson41_VN = '💡 Phần này yêu cầu bạn chọn câu trả lời đúng để điền vào chỗ trống bằng cách xác định liên kết giới từ nào là hoặc cần thiết.';
  final String lesson42_VN = '💡 Với những câu yêu cầu chọn giới từ chính xác, bạn cần làm quen với cách sử dụng giới từ. Điều này sẽ giúp bạn loại bỏ những câu trả lời sai một cách nhanh chóng. Ví dụ, chúng ta thường sử dụng giới từ "at" cho một thời điểm chính xác; "in" cho tháng, năm, thế kỷ và thời gian dài; "on" cho ngày và ngày.\n\n💡 Đối với câu hỏi kiểm tra liên từ, bạn cần so sánh hai nửa của câu và xem xét mối quan hệ của chúng. Sử dụng thông tin này để giúp bạn chọn kết hợp chính xác.';
}

class _Part7{
  final String lesson11_VN = '💡 Trong phần này, bạn được yêu cầu đọc các đoạn văn khác nhau và sau đó trả lời các câu hỏi thông tin cụ thể liên quan đến chúng bằng cách sử dụng kỹ thuật Scanning.';
  final String lesson12_VN = '💡 Đọc câu hỏi và gạch dưới từ khóa.\n\n💡 Đọc lướt qua đoạn văn để tìm thông tin cần thiết\n\n💡 Chọn câu trả lời đúng.';
  final String lesson21_VN = '💡 Bạn phải đọc các đoạn văn khác nhau và sau đó trả lời các câu hỏi về từ vựng, ý chính và suy luận liên quan đến các đoạn văn này.';
  final String lesson22_VN = '💡 Với các câu hỏi về từ vựng, hãy đọc các câu xung quanh từ mục tiêu để cố gắng đoán nghĩa. Các câu hỏi từ vựng đôi khi sử dụng từ vựng khó. Nếu bạn không biết tất cả các từ, hãy bỏ qua những từ bạn biết mà không trả lời được câu hỏi. Điều này sẽ tăng cơ hội đoán thành công của bạn.\n\n💡 Với các câu hỏi về ý chính, bạn nên đọc lướt qua đoạn văn để xác nhận lựa chọn câu trả lời có khả năng nhất. Ngoài ra, bạn có thể trả lời các câu hỏi cụ thể và từ vựng trước để giúp bạn trả lời các câu hỏi về ý chính chính xác hơn.\n\n💡 Với các câu hỏi suy luận, hãy tìm các từ hoặc ý trong đoạn văn liên quan đến những điều được ghi trong mỗi lựa chọn trả lời.';
  final String lesson31_VN = '💡 Với các câu hỏi "NOT", bạn được yêu cầu chọn câu trả lời không đúng hoặc được đề cập.\n\n💡 Với các câu hỏi về tên, số, ngày và giờ, bạn phải chọn các phương án đúng để đưa ra câu trả lời cho câu hỏi về tên, số, ngày tháng và thời gian.';
  final String lesson32_VN = '💡 Để câu hỏi "NOT" kéo dài: Trả lời các câu hỏi khác có thể giúp bạn trả lời câu hỏi "NOT" hoặc biết chỗ nào trong đoạn văn để tìm câu trả lời. Bên cạnh đó, hãy bỏ qua các phương án có ý nghĩa tương tự trong đoạn văn (bạn cần tìm câu KHÔNG đúng). Phương án bạn không tìm thấy là câu trả lời đúng.\n\n💡 Với các câu hỏi về tên, số, ngày và giờ, hãy đọc lướt qua đoạn văn để tìm câu trả lời đúng.';
  final String lesson41_VN = '💡 Trong phần này, bạn sẽ được yêu cầu trả lời các câu hỏi liên quan đến biểu đồ, bảng hoặc biểu mẫu. Bạn cũng phải xử lý các câu hỏi liên quan đến đoạn văn đôi và đoạn ba.';
  final String lesson42_VN = '💡 Với các câu hỏi liên quan đến biểu đồ, bảng và biểu mẫu:\n\n+ Bạn cần hiểu các phần của biểu đồ, bảng và biểu mẫu. Điều này sẽ giúp bạn nhanh chóng xác định các phần của đoạn văn/biểu đồ/bảng có thể tìm thấy thông tin bạn cần.\n\n+ Đọc lướt câu hỏi và đoạn văn để tìm thông tin nhanh chóng. Điều này sẽ giúp bạn xác định phần nào của văn bản được đề cập đến. Sau đó so sánh các lựa chọn câu trả lời với phần đó của biểu đồ, bảng biểu mẫu.\n\n💡 Lưu ý: Hãy cẩn thận với "chữ in nhỏ": Biểu đồ, bảng và biểu mẫu có thể bao gồm ghi chú hoặc thông tin bổ sung ở cuối. Kiểm tra điều này trước khi chọn một câu trả lời phạm sai lầm không cần thiết. để tránh mắc phải những lỗi không đáng có.\n\n💡 Với những câu hỏi liên quan đến đoạn văn kép và đoạn văn ba, hãy để ý thông tin liên kết giữa các văn bản. Trong mỗi đoạn văn đôi và ba, sẽ có ít nhất một câu hỏi yêu cầu bạn xem hai hoặc ba văn bản và kết nối thông tin. Điều quan trọng là đọc hai hoặc ba đoạn trước khi trả lời câu hỏi.';
}